### ISSUE TITLE
[Enhancement] Disable Status

### ISSUE THREAD

**Issue by PoorLatency** [dolutattoo/dolu_hud#3]
Is it possible you can add the ability to disable the hunger, thirst, stress, and drunk for people who don't use it?

**Comment by PoorLatency** [comment]
Any news on this?

**Comment by DoluTattoo** [comment]
Since commit [298094](https://github.com/dolutattoo/dolu_hud/commit/298094ada4974b811605cc42c0e882a263d00743), unused status won't show up.
