### ISSUE TITLE
A few changes that could be nice to have.

### ISSUE THREAD

**Issue by SumnDaiy** [dolutattoo/dolu_hud#6]
- [x] Animations for the circles so it doesn't just snap to new value

- [x] Adding ID to to HUD
- [x] Changing K (seatbelt) to B since ox_inventory uses it to open Trunk/glovebox etc (and since it was made for ox_core why wouldn't people use ox_inventory)
- [x] A new icon for fuel for Electric cars (battery)
- [x] Check if player is in car before being able to buckle up
- [x] If player is not in car automatically set seatbelt to off (in case a player dies in the car)

**Comment by DoluTattoo** [comment]
Thanks a lot for the suggestions!
I'll definitely look into it once I have free time.
If anyone want to work on it do not hesitate to do Pull Requests <3

**Comment by SumnDaiy** [comment]
I did all of the above, was trying to make RPM ProgressBar smoother but couldn't figure it out.
Hopefully you're happy with my changes.

**Comment by SumnDaiy** [comment]
More TODO:

- [x] Make RPM ProgressBar smoother

- [x] A little touch for Informations.tsx so it looks better

- [x] Change bottom left text to a better color / add shadow, so if the enviroment is too bright its still visible.
